"""
Generate the acortical/control Mask-A rapid-learning figure data (fig:ac_rapid, fig:ac_oa_supp).

Computes per-genotype (Acortical / Control) Mask-A learning metrics and the Mask-O baseline,
and stores the example sessions used for the raster/traverse panels. Bootstrap curve fitting is
deferred to ``gen_curve_fits.py`` (this script writes the ``"<base> fit input"`` payloads).

Saved keys
----------
"{gt} Mask A {data_type}"                    : per-animal Mask-A metric arrays (duration / turn error rate / errors), gt in {Acortical, Control}.
"{gt} Mask A reward intervals|sortie counts|tiles per corridor" : per-animal Mask-A behavioral summaries.
"{gt} Mask O reward intervals|sortie counts|speed|tiles per corridor|first hour reward" : Mask-O baseline summaries.
"Acortical A example|Control A example {bout steps|tile steps|bout meta|manifest}" : flat per-bout/per-tile
                                                                 tables for the raster/traverse panels
                                                                 (.parquet); the manifest's `cohort_row`
                                                                 gives each example's row in the
                                                                 whole-cohort metric arrays.
See docs/data_contracts.md §12.

Run (m_maze env, from scripts/, repo on PYTHONPATH):
    python gen_acortical_learning.py --overwrite [--seed 0]
"""
import pandas as pd
import manhattan_maze as mm
from manhattan_maze import utils
from manhattan_maze import mask_d
import argparse
import numpy as np
import config


def main():
    parser = argparse.ArgumentParser(description="Generate figure data")
    parser.add_argument("-ow", "--overwrite", action=argparse.BooleanOptionalAction)
    parser.add_argument("--seed", type=int, default=0,
                        help="RNG seed for example-animal selection; any seed gives qualitatively identical figures (R11).")
    args = parser.parse_args()
    overwrite = args.overwrite
    np.random.seed(args.seed)  # controls random example-animal selection only (R11)

    ## shared paths and DataLoader configuration (see scripts/config.py)
    save_dir = config.SAVE_DIR
    data = mm.DataLoader(config.DATA_DIR, **config.DATALOADER_KWARGS)
    mdf = data.metadata
    acortical_mdf = mdf[mdf.Genotype=="HO"]
    control_mdf = mdf[mdf.Genotype=="WT"]
    a_roundtrips= 10 # minimum number of roundtrips to be included in figure 2, default 15
    oe_roundtrips = 10
    n_examples = 2 # number of examples to plot for visualization
    maskd_special_params = mask_d.MaskDSpec()

    print("Processing Acortical learning data...")
    # === Acortical learning summary table (which masks each animal learned) ===
    # Read the per-(animal, mask) reward-count table that classifies animals as
    # highly-rewarded / long-term; it is generated by the standalone prerequisite
    # gen_count_df.py (R7) and used here to pick cohorts below.
    count_df = pd.read_csv(f"{save_dir}/Acortical_learning_count_df.csv")

    print("Processing Mask A learning data...")
    # === Mask A first-exposure cohorts and example sessions (acortical vs control) ===
    # Select the highly-rewarded acortical animals and the control animals, take
    # each animal's strict-first Mask-A session, and randomly pick example sessions
    # per group (RNG fixed by --seed) for the example-trajectory panels.
    # Main figure data are based on highly rewarded animals
    acortical_a_animals = count_df[count_df.Mask=="A"].Highly_rewarded_animal_list.values[0].split(", ")
    # get their first sessions
    acortical_a_sub_df = acortical_mdf[acortical_mdf.Animal.isin(acortical_a_animals)]

    acortical_first_a = utils.get_first_learning_session(data, acortical_a_sub_df, mask_name="A", strict_first=True, e_trained="No") # using the strict first a for main figure
    print(f"Number of acortical animals in Mask A: {len(acortical_first_a)}")
    [print(s.name) for s in acortical_first_a]

    control_first_a = utils.get_first_learning_session(data, control_mdf, mask_name="A", strict_first=True, e_trained="No")
    print(f"Number of control animals in Mask A: {len(control_first_a)}")
    [print(s.name) for s in control_first_a]

    acortical_example_indices = np.random.choice(np.arange(len(acortical_first_a)), n_examples, replace=False)
    acortical_a_examples = [acortical_first_a[i] for i in acortical_example_indices]
    control_example_indices = np.random.choice(np.arange(len(control_first_a)), n_examples, replace=False)
    control_a_examples = [control_first_a[i] for i in control_example_indices]
    # R8 replacement: flat per-bout/per-tile tables for the same example sessions. The
    # selection indices are carried through as the manifest's `cohort_row`, which is the
    # row each example occupies in the whole-cohort metric arrays -- previously recovered
    # in plot_ac_rapid.py by a numerical identity join on traverse durations.
    for base, sessions, cohort_rows in (("Acortical A example", acortical_a_examples, acortical_example_indices),
                                        ("Control A example", control_a_examples, control_example_indices)):
        for suffix, table in utils.get_example_session_tables(sessions, cache=base,
                                                             cohort_rows=cohort_rows).items():
            utils.save_modular_data(f"{base} {suffix}", table, save_dir, overwrite=overwrite)

    # === Mask A per-traverse learning curves (acortical vs control) ===
    # For each metric, build an (n_animals x n_traverses) NaN-padded array of the
    # per-traverse values; these feed the Mask-A learning-curve panels.
    # get the traverse duration and turn error data for Mask A for both groups
    # "tile/corridor error rate" = per-step non-progress fraction ([0,1], chance ~0.5); plain counts
    # kept alongside during the rate migration (removed in cleanup).
    for data_type in ["duration", "turn error rate", "speed", "tile error", "corridor error",
                      "tile error rate", "corridor error rate"]:
        for gt, sessions in zip(["Acortical", "Control"], [acortical_first_a, control_first_a]):
            traverse_data = utils.extract_array([s.filter("traverse").get_bout_stats(unit=data_type) for s in sessions], size=a_roundtrips * 2)
            utils.save_modular_data(f"{gt} Mask A {data_type}", traverse_data, save_dir, overwrite=overwrite)

    # === Mask A per-reward (journey-sliced) metrics: sorties, reward intervals, tiles/corridor ===
    # Quantities measured per reward/journey rather than per traverse, plus the
    # tiles-per-corridor scanning metric on the first journey.
    # sliced data
    for gt, sessions in zip(["Acortical", "Control"], [acortical_first_a, control_first_a]):
        sortie_array = utils.extract_array([s.get_slice_stats(unit="sortie counts") for s in sessions], size=a_roundtrips * 2)
        utils.save_modular_data(f"{gt} Mask A sortie counts", sortie_array, save_dir, overwrite=overwrite)
        interval_array = utils.extract_array([s.get_slice_stats(unit="reward intervals") for s in sessions], size=a_roundtrips * 2)
        utils.save_modular_data(f"{gt} Mask A reward intervals", interval_array, save_dir, overwrite=overwrite)
        # tiles per corridor
        tpc_list = [s.slice_by_traverse_idx(None, 1).get_tiles_per_corridor() for s in sessions]
        utils.save_modular_data(f"{gt} Mask A tiles per corridor", np.array(tpc_list), save_dir, overwrite=overwrite)
        # Pre-reward first-journey directional persistence (beta_hat): the latent-learning
        # readout, compared against the memoryless walker's 0.5 in the fig:ac_oa_supp panel
        # beside the wildtype curve from gen_wildtype_two_day_data.py. Same estimator: one
        # 20%-of-journey window per grid point, fully-supported positions only (mode="valid"),
        # no post-hoc smoothing (see the gen_wildtype_two_day_data.py comment).
        beta_curve = utils.first_journey_forward_bias_curve(sessions)
        utils.save_modular_data(f"{gt} A first journey forward bias", beta_curve, save_dir, overwrite=overwrite)
        _beta_ok = beta_curve[1][~np.isnan(beta_curve[1])]
        print(f"{gt} Mask A first-journey beta_hat: "
              + (f"{_beta_ok[0]:.3f} -> {_beta_ok[-1]:.3f}" if _beta_ok.size else "all points empty")
              + f" ({_beta_ok.size}/{beta_curve.shape[1]} points populated, cohort n={len(sessions)})")

    # === Mask A exponential curve-fit results (bootstrap CIs) for duration & turn error ===
    # Animal-level bootstrap fit of the learning-curve model for each metric and
    # group; the (bs, ds, summary_df, bootstrap_curves) tuple drives the fitted
    # curve + CI band and the D_inf/D_0/delta (E_inf/E_0/epsilon) parameter panels.
    # generate data for curvefit results:

    # data_type, params_name, p0, lower_bounds, upper_bounds
    for sub_tuple in config.CURVE_FIT_SPECS:
        data_type, params_name, _params_latex, p0, lower_bounds, upper_bounds = sub_tuple
        for gt, sessions in zip(["Acortical", "Control"], [acortical_first_a, control_first_a]):
            data_df = utils.get_traverse_data_df(sessions, data_type)
            data_df["Genotype"] = gt
            # Save the fit input; the centralised gen_curve_fits.py step produces the
            # "{gt} A {data_type} fit results" cache with one shared bootstrap seed.
            utils.save_curve_fit_input(f"{gt} A {data_type}", data_df, data_type, a_roundtrips*2, save_dir, overwrite=overwrite)


    print("Processing Mask O Supplementary data...")
    # === Mask O supplementary: reward intervals, first-hour reward count, sorties, tiles/corridor ===
    # First-exposure Mask-O sessions for both groups; per-session reward intervals,
    # count of rewards obtained in the first hour (3600 s), sortie counts, and
    # tiles-per-corridor for the Mask-O control supplementary figure.
    # this gives a list of animals that we are going to study
    acortical_o_sessions = utils.get_first_learning_session(data, sub_mdf=acortical_mdf[acortical_mdf.Nickname.str.contains("a1")], mask_name="O", strict_first=True)
    control_o_sessions = utils.get_first_learning_session(data, sub_mdf=control_mdf[control_mdf.Nickname.str.contains("a1")], mask_name="O", strict_first=True)

    for gt, sessions in zip(["Acortical", "Control"], [acortical_o_sessions, control_o_sessions]):
        int_list = [s.reward_interval_seconds for s in sessions]
        utils.save_modular_data(f"{gt} Mask O reward intervals", utils.extract_array(int_list, size=oe_roundtrips * 2),
                                save_dir, overwrite=overwrite)
        first_hour_rewards = [np.sum(np.cumsum(array)<3600) for array in int_list]  # 3600 s = 1 hour (reward intervals in seconds) (R3)
        utils.save_modular_data(f"{gt} Mask O first hour reward", np.array(first_hour_rewards), save_dir, overwrite=overwrite)
        sortie_list = [s.get_slice_stats("sortie counts") for s in sessions]
        utils.save_modular_data(f"{gt} Mask O sortie counts", utils.extract_array(sortie_list, size=oe_roundtrips * 2), save_dir, overwrite=overwrite)
        # tiles per corridor:
        tpc_list = [s.slice_by_traverse_idx(None, 1).get_tiles_per_corridor() for s in sessions]
        utils.save_modular_data(f"{gt} Mask O tiles per corridor", np.array(tpc_list), save_dir, overwrite=overwrite)
        # speed
        speed_list = [s.filter("traverse").get_bout_stats(unit="speed") for s in sessions]
        utils.save_modular_data(f"{gt} Mask O speed", utils.extract_array(speed_list, size=oe_roundtrips*2), save_dir, overwrite=overwrite)

if __name__ == "__main__":
    main()
